### ISSUE TITLE
UnicodeError

### ISSUE THREAD

**Issue by zopyx** [plone/bobtemplates.plone#243] opened 2017-11-30 07:53 UTC
A fresh checkout from master gives me this:

```
(cats.policy) ajung@dev ~/sandboxes/bobtemplates.plone (master) $ bin/mrbob bobtemplates.plone:addon -O collective.foo

Welcome to mr.bob interactive mode. Before we generate directory structure, some questions need to be answered.

Answer with a question mark to display help.
Values in square brackets at the end of the questions show the default value if there is no answer.


Traceback (most recent call last):
  File "bin/mrbob", line 11, in <module>
    load_entry_point('mr.bob', 'console_scripts', 'mrbob')()
  File "/home/ajung/sandboxes/bobtemplates.plone/lib/python2.7/site-packages/mr.bob-0.1.2-py2.7.egg/mrbob/cli.py", line 172, in main
    c.ask_questions()
  File "/home/ajung/sandboxes/bobtemplates.plone/lib/python2.7/site-packages/mr.bob-0.1.2-py2.7.egg/mrbob/configurator.py", line 231, in ask_questions
    self.variables[question.name] = question.ask(self)
  File "/home/ajung/sandboxes/bobtemplates.plone/lib/python2.7/site-packages/mr.bob-0.1.2-py2.7.egg/mrbob/configurator.py", line 303, in ask
    question = six.u("--> %s [%s]: ") % (self.question, self.default)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 12: ordinal not in range(128)

```

**Comment by MrTango** [comment] 2018-01-07 11:33
With the current code I can't reproduce this, so I will close this.
Feel free to reopen if you still have problems.

**Closed by MrTango** 2018-01-07 11:33 UTC
